feat: add layout mobile version first screen
annkainova/twitter-project pull request #3
Opened 2024-02-14 20:15 UTC by annkainova

2024-02-15 10:01 UTC, burtovoy requested changes
Круто. Единственное, нужно только sass оставить в репе

2024-02-18 16:38 UTC, annkainova commented
Мне нужно оставить папку  с SASS файлами, а СSS удалить? 
А почему CSS не нужен в main?

2024-02-18 16:43 UTC, burtovoy commented
Да. В репе должны быть только те файлы, с которыми мы работаем. Иначе получается на одно изменение 2 файла меняется. Плюс, зачем нам css если мы работаем с sass

2024-02-18 16:59 UTC, annkainova commented
Удалила файлы CSS и JS файл с прошлой задачи

2024-02-18 23:20 UTC, merged